myjob/extapps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

myjob/mmorder/urls.py
from django.urls import path

from mmorder.views import *
from mmorder.api_views import *

app_name = 'mmorder'

urlpatterns = [
    path('log/', login, name='log'),
    path('reg/', register, name='reg'),
    path('mine/', mine, name='mine'),
    path('louout/', louout, name='louout'),
    path('shop/', shop, name='shop'),
    path('shop_message/<typeid>', shop_message, name='shop_message'),
    path('addcart/', add_shopping),
    path('addtocart/',add_to_cart),
    path('subcart/', sub_shopping),
    path('subfromcart/',sub_from_cart),
    path('cart/', go_cart,name='go_cart'),
    path('payed/',pay),
    path('makeorder/',make_order),
    path('orderdetail/',order_detail),
    path('changecartstate/',change_cart_state),
    path('allselect/',cart_all_select),
    path('index/', index),
    path('update_order/', update_order),
    path('pay_result/', pay_result)
]

myjob/myjob/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('mm_order/',include('mmorder.urls',namespace='mm_order'))
]

myjob/mmorder/models.py
from django.contrib.auth.models import User
from django.db import models

from mmorder.views_constant import ORDER_STATUS_NOT_PAY


class FoodsType(models.Model):
    typename = models.CharField(max_length=20)
    note = models.CharField(max_length=50, null=True)

    class Meta:
        db_table = 'mm_foodtype'


# class Category(models.Model):
#     name = models.CharField(max_length=50,
#                             verbose_name='分类名')
#     order_seq = models.IntegerField(verbose_name='排行')



class Foods(models.Model):
    fid = models.IntegerField(primary_key=True)
    fname = models.CharField(max_length=50)
    fcategory = models.CharField(max_length=20)
    fprice = models.FloatField()
    fpopnum = models.IntegerField()
    fimg = models.CharField(max_length=100)

    class Meta:
        db_table = 'mm_foods'


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.FloatField()
    state = models.IntegerField(default=ORDER_STATUS_NOT_PAY)
    time = models.DateTimeField(auto_now=True)


    class Meta:
        db_table = 'mm_order'


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    foods = models.ForeignKey(Foods, on_delete=models.CASCADE)
    cart_foods_num = models.IntegerField(default=1)
    is_selected = models.BooleanField(default=True)

    class Meta:
        db_table = 'mm_cart'


class Orderdetail(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    foods = models.ForeignKey(Foods, on_delete=models.CASCADE)
    order_foods_num = models.IntegerField()

    class Meta:
        db_table = 'mm_orderdetail'

myjob/mmorder/views.py
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from mmorder.models import FoodsType, Foods, Cart, Order, Orderdetail
from mmorder.views_constant import ORDER_STATUS_NOT_PAY, ORDER_STATUS_NOT_SEND


# 跳转到商品页面
def shop(request):
    return redirect(reverse('mm_order:shop_message', kwargs={"typeid": 3}))


# 详细商品
def shop_message(request, typeid):
    foodtypes = FoodsType.objects.all()
    foodtype = FoodsType.objects.get(pk=typeid)
    foods_list = Foods.objects.filter(fcategory=foodtype.typename)
    for foods in foods_list:
        carts = Cart.objects.filter(foods=foods)
        if carts.exists():
            cart = carts.first()
            foods.cart_food_num = cart.cart_foods_num
    data = {
        'foodtypes': foodtypes,
        'foods_list': foods_list
    }
    return render(request, 'shop.html', data)


# 跳转到购物车
def go_cart(request):
    carts = Cart.objects.filter(user=request.user)
    data = {
        "carts": carts,
        "total_price": total_price(carts)
    }
    return render(request, 'cart.html', data)


# 添加到购物车
def add_to_cart(request):
    foodsid = request.GET.get("foodsid")
    foods = Foods.objects.filter(fid=foodsid).first()
    carts = Cart.objects.filter(user=request.user).filter(foods_id=foodsid)
    if carts:
        cart = carts.first()
        cart.cart_foods_num = cart.cart_foods_num + 1
    else:
        cart = Cart()
        cart.user = request.user
        cart.foods = foods
        cart.cart_foods_num = 1

    cart.save()
    data = {
        "cart_foods_num": cart.cart_foods_num
    }
    return JsonResponse(data)


# 购物车减去商品
def sub_from_cart(request):
    foodsid = request.GET.get("foodsid")

    carts = Cart.objects.filter(user=request.user).filter(foods=foodsid)
    cart = carts.first()

    data = {}

    if cart.cart_foods_num > 1:
        cart.cart_foods_num = cart.cart_foods_num - 1
        cart.save()
        data["cart_foods_num"] = cart.cart_foods_num
    else:
        cart.delete()
        data["cart_foods_num"] = 0

    return JsonResponse(data)


# 在购物车页面点击加号
def add_shopping(request):
    cartid = request.GET.get("cartid")
    cart = Cart.objects.get(pk=cartid)
    cart.cart_foods_num = cart.cart_foods_num + 1
    cart.save()

    user_id = request.session.get("user_id")
    user = User.objects.get(pk=user_id)
    carts = Cart.objects.filter(user=user)
    totalprice = total_price(carts)

    data = {
        "total_price": totalprice,
        "cart_foods_num": cart.cart_foods_num,
        'status': 200
    }

    return JsonResponse(data)


# 购物车点击减号
def sub_shopping(request):
    cartid = request.GET.get("cartid")
    cart = Cart.objects.get(pk=cartid)
    cart.cart_foods_num = cart.cart_foods_num-1
    cart.save()

    if cart.cart_foods_num == 0:
        cart.delete()

    user_id = request.session.get("user_id")
    user = User.objects.get(pk=user_id)
    carts = Cart.objects.filter(user=user)
    totalprice = total_price(carts)
    data = {
        "total_price": totalprice,
        "cart_foods_num": cart.cart_foods_num,
        'status': 200,
    }

    return JsonResponse(data)


# 在购物车页面点击全选
def cart_all_select(request):
    unselected = request.GET.get("cart_list")

    if unselected:
        unselected_list = unselected.split('#')
        for cartid in unselected_list:
            cart = Cart.objects.get(pk=cartid)
            cart.is_selected = True
            cart.save()

    user_id = request.session.get("user_id")
    user = User.objects.get(pk=user_id)
    carts = Cart.objects.filter(user=user)
    totalprice = total_price(carts)

    data = {
        "total_price": totalprice,
        'status': 200,
    }
    return JsonResponse(data)


# 在购物车页面点击购物车条目的选中状态
def change_cart_state(request):
    cartid = request.GET.get("cartid")
    cart = Cart.objects.get(pk=cartid)
    cart.is_selected = not cart.is_selected
    cart.save()

    carts = Cart.objects.filter(user=request.user)
    is_all_select = True
    for cart in carts:
        if not cart.is_selected:
            is_all_select = False
            break

    data = {
        "cart_is_select": cart.is_selected,
        "total_price": total_price(carts),
        "is_all_select": is_all_select,
        'status': 200,
    }

    return JsonResponse(data)


# 下单
def make_order(request):
    order = Order()
    order.user = request.user
    carts = Cart.objects.filter(user=request.user).filter(is_selected=True)
    order.price = total_price(carts)
    order.save()

    for cart in carts:
        orderdetail = Orderdetail()
        orderdetail.order = order
        orderdetail.foods = cart.foods
        orderdetail.order_foods_num = cart.cart_foods_num
        orderdetail.save()
        cart.delete()

    data = {
        'order_id': order.id,
        'status': 200,
    }
    return JsonResponse(data)


# 计算商品总价
def total_price(carts):
    total = 0.0
    for cart in carts:
        if cart.is_selected:   # 判断该记录是否被选中
            total += cart.foods.fprice * cart.cart_foods_num

    return "{:.2f}".format(total)


# 显示订单详情页面
def order_detail(request):
    orderid = request.GET.get("orderid")
    order = Order.objects.get(pk=orderid)
    data = {
        'orders': order,
        'status': 200,
    }

    return render(request, 'order_detail.html', data)


def order_not_pay(request):
    orders = Order.objects.filter(state=ORDER_STATUS_NOT_PAY)
    data = {
        'orders': orders,
        'status': 200
    }

    return render(request, 'order_list_not_pay.html', data)


def pay(request):
    orderid = request.GET.get('orderid')
    order = Order.objects.get(pk=orderid)
    order.state = ORDER_STATUS_NOT_SEND
    order.save()
    data = {
        'status': 200,
        'orderprice': order.price,
    }
    return JsonResponse(data)


def mine(request):
    print("**********")
    user_id = request.session.get('user_id')
    print(user_id,"******2******")
    data = {
        "is_login":False
    }
    if user_id:
        user = User.objects.get(pk=user_id)
        data["is_login"] = True
        data["username"] = user.username
        print(data,"**********")
    return render(request, 'mine.html', data)

#  注册
def register(request):
    if request.method == "GET":
        return render(request, 'register.html')
    elif request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        email = request.POST.get("email")
        # icon = request.FILES.get("icon")
        if not all([username]):
            message = '用户名不能为空'
            return render(request, 'register.html', locals())
        name_1 = User.objects.filter(username=username)
        if name_1:  # 用户名唯一
            message = '用户名存在'
            return render(request, 'register.html', locals())
        if not all([email]):
            message = '邮箱不能为空'
            return render(request, 'register.html', locals())
        email_1 = User.objects.filter(email=email)
        if email_1:
            message = '邮箱存在'
            return render(request, 'register.html', locals())
        if not all([password]):
            message = '密码不能为空'
            return render(request, 'register.html', locals())
        User.objects.create_user(username, email, password)
        return render(request, 'login.html')


#  登录
def login(request):
    if request.method == "GET":
        # error_message =request.session.get("error_message")
        # if error_message:
        #     del request.session["error_message"]
        return render(request, 'login.html')
    elif request.method =="POST":
        errors = {'msg':''}
        username = request.POST.get("username")
        password = request.POST.get("password")
        valid_code =request.POST.get("valid_code") #填写验证码
        queryset = User.objects.filter(username=username)
        if not queryset.exists():
            errors['msg'] = '%s 用户不存在，请先注册!' % username
        else:
            user = queryset.first()
            print(user.id,"*****3*****")
            # 验证口令
            if check_password(password, user.password):
                # 将登录后的信息存入到session中
                # request.session['login_user'] = {
                #     'id': user.id,
                #     'username': user.username,
                # }
                request.session["user_id"] = user.id
                return redirect(reverse('mm_order:mine'))
            else:
                errors['msg'] = '登录口令不正确！'
    return render(request, 'login.html', locals())

def louout(request):
    request.session.flush()
    return redirect(reverse("mm_order:mine"))

myjob/mmorder/templates/cart.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购物车</title>
    <script type="text/javascript" src="{%static 'js/jquery.js'  %}"></script>
    <script>
        $(function () {
            $(".confirm").click(function () {
                console.log("change state");
                var $confirm = $(this);
                var $li = $confirm.parents("li");
                var cartid = $li.attr('cartid');
                $.getJSON("/mm_order/changecartstate/",{'cartid':cartid},function (data) {
                    console.log(data);
                    $("#total_price").html(data['total_price']);
                    if (data['cart_is_select']){
                        $confirm.find('input').prop("checked",true);
                    }else{
                        $confirm.find('input').prop("checked", false);
                    }
                    if(data['is_all_select']){
                        $(".all_select input").prop("checked",true);
                    }else{
                        $(".all_select input").prop("checked", false);
                    }
                })
            })
            $(".addshopping").click(function () {
                var $add = $(this);
                var $li = $add.parents("li");
                var cartid = $li.attr("cartid");
                $.getJSON("/mm_order/addcart/",{"cartid":cartid},function (data) {
                    console.log(data);
                    $("#total_price").html(data['total_price']);
                    $add.prev('span').html(data['cart_foods_num']);
                })
            })
            $(".subshopping").click(function () {
                var $sub = $(this);
                var $li = $sub.parents("li");
                var cartid = $li.attr("cartid");
                $.getJSON("/mm_order/subcart/",{"cartid":cartid},function (data) {
                    console.log(data)
                    $("#total_price").html(data['total_price']);
                     if(data["cart_foods_num"]>0){
                         $sub.next('span').html(data['cart_foods_num']);
                     }else{
                         $li.remove();
                     }
                })
            })
            $(".all_select").click(function () {
                var $all_select = $(this);
                if($all_select.find("input").prop("checked")){
                    $all_select.find('input').removeAttr("checked", true);
                }else {
                     $all_select.find('input').prop("checked",true);
                }
                var unselect_list = []
                $(".confirm").each(function () {
                    var $confirm = $(this);
                    var cartid = $confirm.parents("li").attr("cartid");
                    if(!($confirm.find("span").find('input').prop("checked"))){
                        unselect_list.push(cartid);
                    }
                })
                if(unselect_list.length > 0){
                    $.getJSON("/mm_order/allselect/",{"cart_list":unselect_list.join("#")},function (data) {
                        console.log(data);
                        $(".confirm").find("span").find('input').prop("checked",true);
                        $all_select.find('input').removeAttr("checked", true);
                        $("#total_price").html(data["total_price"]);
                    })
                }
            })
            $("#make_order").click(function () {
                var select_list = [];
                $(".confirm").each(function () {
                    var $confirm = $(this);
                    var cartid = $confirm.parents("li").attr("cartid");
                    if($confirm.find("input").prop("checked")){
                        select_list.push(cartid);
                    }
                })
                if(select_list.length === 0){
                    alert("未选中任何条目，不能下单！");
                    return;
                }
                $.getJSON("/mm_order/makeorder/",function (data) {
                    console.log(data);
                    window.open("/mm_order/orderdetail/?orderid=" + data['order_id'],target="_self");
                })
            })
        })
    </script>
</head>
<body>
    <a href="">首页</a>
    <a href=" {% url 'mm_order:shop_message' 1 %} ">点餐</a>
    <a href="">个人中心</a>
    <br/>
    <br/>
    {% for cart in carts %}
        <li class="menuList" cartid="{{ cart.id }}">
            <div>
                <span class="confirm">
                    <input type="checkbox" checked="true">
                </span>
            </div>
            <img src="{{ cart.foods.fimg }}"><br/>
            <span>{{ cart.foods.fname }}</span>
            <button class="subshopping">-</button>
            <span>{{ cart.cart_foods_num }}</span>
            <button class="addshopping">+</button>
            <br/>
        </li>
    {% endfor %}
    <div class="payTheBill">
        <div class="all_select">
                <span><input type="checkbox"></span>
        </div>
        <span>共计：</span>
        <span id="total_price">{{ total_price }}</span>
        <button id="make_order">下单</button>
    </div>
    
</body>
</html>

myjob/mmorder/templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="price" placeholder="请输入'{{ orderprice }}'元">
        <input type="submit" value="支付">
    </form>
</body>
</html>

myjob/mmorder/templates/login.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Lowin</title>
	<link rel="stylesheet" href="/static/log/css/auth.css">
</head>

<body>
	<div class="lowin">
		<div class="lowin-brand">
			<img src="/static/log/imgs/kodinger.jpg" alt="logo">
		</div>
		<div class="lowin-wrapper">
			<div class="lowin-box lowin-login">
				<div class="lowin-box-inner">
                    <div class="error">
                    {% if errors %}
                    <h4  style="margin-left: 200px; color: #ff6464" >{{ errors.msg }}</h4>
                    {% endif %}
					<form action="{% url 'mm_order:log' %}" method="post">
                        {% csrf_token %}
						<p>Sign in to continue</p>
						<div class="lowin-group">
							<label>Username <a href="#" class="login-back-link">Sign in?</a></label>
							<input type="text" autocomplete="username" name="username" class="lowin-input">
						</div>
						<div class="lowin-group password-group">
							<label>Password <a href="#" class="forgot-link">Forgot Password?</a></label>
							<input type="password" name="password" autocomplete="current-password" class="lowin-input">
						</div>
{#						<button type="submit" class="lowin-btn login-btn">#}
{#							Sign In#}
{#						</button>#}
                        <input type="submit" value="Sign In" class="lowin-btn">
						<div class="text-foot">
							Don't have an account? <a href="{% url 'mm_order:reg' %}" class="register-link">Register</a>
						</div>
					</form>
                    </div>
				</div>
			</div>
		</div>
	</div>

	<script src="/static/log/js/auth.js"></script>
	<script>
		Auth.init({
			login_url: '#login',
			forgot_url: '#forgot'
		});
	</script>
</body>
</html>

myjob/mmorder/templates/mine.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <link rel="stylesheet" href="/static/log/css/mine.css">
</head>
<body style="background-color: #ebedef">
<div class="div1">
    <div id="div3"><img src="/static/log/imgs/head.jpg"></div>
    <div id="div2">
        {% if is_login %}
        <p style="color: black">{{ username }}</p>
        {% else %}
        <p><a href="{% url 'mm_order:log' %}">登录</a></p>
        {% endif %}
    </div>
    <div id="div4">
        {% if is_login %}
    <p>
    <a href="{% url 'mm_order:louout' %}">退出</a>
    </p>
{% endif %}
    </div>
<div id="div5">
        <div id="div6">
        <a href="" id="a1">
        <img  src="/static/log/imgs/order.png" id="img1" >全部订单</a>
        <a href="" id="a2">
        <img  src="/static/log/imgs/money.png" id="img2" >待付款</a>
        <a href="" id="a3">
        <img  src="/static/log/imgs/nav7.png" id="img3" >待使用</a>
        <a href="" id="a4">
        <img  src="/static/log/imgs/nav6.png" id="img4" >待评价</a>
        <a href="" id="a5">
        <img  src="/static/log/imgs/nav3.png" id="img5" >退款/售后</a>
        </div>
    </div>
</div>
<div class="div2">
    <h3 id="t1">猜你喜欢</h3>
    <div id="a6"></div>
    <div id="a7"></div>
    <div id="a8"></div>
    <div id="a9"></div>
</div>
<div class="div3">
    <div id="div7">
        <a href="" id="a10"><h2>我的主页</h2></a>
    </div>
    <div id="div8">
        <a href="" id="a10"><h2>我的订单</h2></a>
    </div>
    <div id="div9">
        <h5>全部订单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;>
        </h5>
        <h5>全部订单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;>
        </h5>
        <h5>全部订单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;>
        </h5>
        <h5>全部订单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;>
        </h5>
        <h5>全部订单&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;>
        </h5>

    </div>
</div>
</body>
</html>

myjob/mmorder/templates/order_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
    <script type="text/javascript" src="{%static 'js/jquery.js'  %}"></script>
    <script>
        $(function () {
            $("#alipay").click(function () {
                console.log("支付");
                var orderid = $(this).attr("orderid");
                $.getJSON("/mm_order/payed/",{"orderid":orderid},function (data) {
                    window.open('/mm_order/index/?orderprice=' + data['orderprice'], target='_self');
                })
            })
        })
    </script>
</head>
<body>
        订单编号：{{ orders.id }}
        <br/>
        {% for orderfoods in orders.orderdetail_set.all %}
            <img src="{{ orderfoods.foods.fimg }}">
            <p>{{ orderfoods.foods.fname }}</p>
            商品：{{ orderfoods.order_foods_num }}&nbsp;&nbsp;单价：{{ orderfoods.foods.fprice }}<br/>
        {% endfor %}
        <h6 class="total_price">总价{{ orders.price }}</h6>
        <button orderid="{{ orders.id }}" id="alipay">支付</button>
</body>
</html>

myjob/mmorder/templates/order_list_not_pay.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>未支付订单</title>
    <script type="text/javascript" src="{%static 'js/jquery.js'  %}"></script>
    <script>
        $(function () {
            $(".order").click(function () {
                var $order = $(this);
                var order_id = $order.attr("orderid");
                window.open('/mm_order/orderdetail/?orderid=' + order_id,target="_self")
            })
        })
    </script>
</head>
<body>
    {% for order in orders %}
        <li>
            <ul class="order" orderid="{{ order.id }}">
                订单编号：{{ order.id }} <br/>
                {% for orderfoods in order.orderdetail_set.all %}
                    <li>
                        <img src="{{ orderfoods.foods.fimg }}"><br/>
                        {{ orderfoods.foods.fname }}&nbsp;&nbsp;&nbsp;{{ orderfoods.foods.price }} &nbsp;&nbsp;&nbsp;{{ ordergoods.order_goods_num }}
                    </li>
                {% endfor %}

            </ul>
        </li>
    {% endfor %}

</body>
</html>

myjob/mmorder/templates/register.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>Lowin</title>
	<link rel="stylesheet" href="/static/log/css/auth.css">
</head>

<body>
	<div class="lowin">
		<div class="lowin-brand">
			<img src="/static/log/imgs/kodinger.jpg" alt="logo">
		</div>
		<div class="lowin-wrapper">
			<div class="lowin-box lowin-register">
				<div class="lowin-box-inner">
					<form action="{% url 'mmorder:reg' %}" method="post">
                        {% if message %}
                        <div class="alert alert-warning">{{ message }}</div>
                        {% endif %}
                        {% csrf_token %}
						<p>Let's create your account</p>
						<div class="lowin-group">
							<label>Name</label>
							<input type="text" name="username" autocomplete="username" class="lowin-input">
						</div>
						<div class="lowin-group">
							<label>Email</label>
							<input type="email" autocomplete="email" name="email" class="lowin-input">
						</div>
						<div class="lowin-group">
							<label>Password</label>
							<input type="password" name="password" autocomplete="current-password" class="lowin-input">
						</div>
{#						<button class="lowin-btn">#}
{#							Sign Up#}
{#						</button>#}
                        <input type="submit" value="Sign Up" class="lowin-btn">
						<div class="text-foot">
							Already have an account? <a href="" class="login-link">Login</a>
						</div>
					</form>
				</div>
			</div>
		</div>


	</div>

	<script src="/static/log/js/auth.js"></script>
	<script>
		Auth.init({
			login_url: '#login',
			forgot_url: '#forgot'
		});
	</script>
</body>
</html>

myjob/mmorder/templates/shop.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>购买食物</title>
    <script type="text/javascript" src="{%static 'js/jquery.js'  %}"></script>
    <script type="text/javascript">
        $(function() {
            $(".subshopping").click(function() {
                var $sub_button = $(this);
                var span_num = $sub_button.next("span").html();
                if(span_num == "0"){
                    alert("购物车本无此商品!");
                    return;
                }
                var foodsid = $sub_button.attr('foodsid');

                $.get('/mm_order/subfromcart/',{'foodsid':foodsid},function(data) {
                    console.log(data);
                    if (data['status'] === 302){
                        window.open('/mm_order/log/',target='_self');
                        alert('hello')
                    }
                    $sub_button.next('span').html(data['cart_foods_num']);
                })
            })

            $(".addshopping").click(function() {
                var $add = $(this);
                var foodsid = $add.attr('foodsid');

                $.get('/mm_order/addtocart/',{'foodsid':foodsid},function(data) {
                    console.log(data);
                    if (data['status']  === 302){
                        window.open('/mm_order/log/',target='_self');
                    } else{
                        $add.prev('span').html(data['cart_foods_num']);
                    }
                })
            })
        })
    </script>
</head>
<body>
    <a href="">首页</a>
    <a href="{% url 'mm_order:go_cart' %}">购物车</a>
    <a href="">个人中心</a>
    {% for foodtype in foodtypes %}
        <a href="{% url 'mm_order:shop_message' foodtype.id %}" target="_self"><button id="foodtype">{{ foodtype.typename }}</button></a>
    {% endfor %}
    <br/>
    {% for foods in foods_list %}
        {{ foods.fname }}<br/>
        <img src="{{ foods.fimg }}" height=""><br/>
        人气：{{ foods.fpopnum }} &nbsp;&nbsp;价格：{{ foods.fprice }}
        <button foodsid="{{ foods.fid }}" class="subshopping">-</button>
        <span>{% if foods.cart_food_num %}
                {{ foods.cart_food_num }}
                {% else %}
                    0
            {% endif %}
        </span>
        <button foodsid="{{ foods.fid }}" class="addshopping">+</button>
    {% endfor %}
</body>
</html>